### PR TITLE
All Seasons Update + a Few Extra Bits

### PR DESCRIPTION
**Pull request by Jakosaur**

### CODE REVIEW

**Comment by joshhunt** [comment]
I’m on mobile at the moment, but it looks like there’s a syntax error introduced in dlc1.js

**Comment by joshhunt** [comment]
https://deploy-preview-82--destiny-sets.netlify.com/all-seasons

Looks great! I’ll check it out and merge it later when I’m on my computer 🌟

**Comment by Jakosaur** [comment]
I can't seem to view [https://deploy-preview-82--destiny-sets.netlify.com/curse-of-osiris]( https://deploy-preview-82--destiny-sets.netlify.com/curse-of-osiris ) 

Any idea if there's something wrong with it?

**Comment by joshhunt** [comment]
Weird - i definitely saw it working before. Anyway, the "Eververse, Season 2" in dlc1.js is in the wrong format. It should be like `{name: "other", sets: [...eververse stuff...] }`, like the rest.

**Comment by Jakosaur** [comment]
I'll look at that later today when I've got spare time.

**Pull request merged**
