### PR TITLE
 Updating sets with declassified CoO Weapons

### PR DESCRIPTION
**Pull request by alexcpsec**
This should add all the new CoO weapons to their sets. 

There was some guesswork here and there but should be correct.

### CODE REVIEW

**Comment by joshhunt** [comment]
This looks pretty good - thanks for putting this together!

I'm thinking that just one page isnt going to scale very well, so I'm going to add a second CoO page only. If you don't mind, could you create a second file called something like `sets-coo.js`  or something like that, with the same structure but just the CoO/S2 content? And then I could hook up and add a link to it...

Looking great!

**Comment by joshhunt** [comment]
Actually @alexcpsec, do we think that Perfect Paradox is actually a Lost Prophecy weapon? 
My understanding is that it's currently unobtainable and it'll probably come from some quest elsewhere?

I only say that because it doesn't follow the naming convention for the rest of the Lost Prophecy weapons and it doesnt have the same style...

**Comment by alexcpsec** [comment]
Hey, Josh!

1) Sure, I'll work on the CoO page,
2) It is conjecture. People believe the Saint-14 quest for the shotgun will be given by Brother Vance as soon as you get all the 10 other prophecy weapons. Bungie did say that there were 11 prophecy weapons. My suggestion would be to leave it on the Lost Prophecies tab and adjust later if necessary.

**Comment by alexcpsec** [comment]
There you go. I did not remove the S2 specific stuff you had on the original page, as I am not sure if you want to bring the S1 stuff back.

I can add ornaments later if you figure out there is a way to check if we have fulfilled them or not

**Comment by joshhunt** [comment]
Awesome. Might take me a bit to add a new page for it (mobile needs fixing), but should be up within a day or so :)

**Comment by joshhunt** [comment]
Hey @alexcpsec this just went live - do you have a twitter handle I could shout out?

**Comment by alexcpsec** [comment]
Same as the github user (@alexcpsec)

I just say the raid lair stuff was declassified. will do them later today.

**Comment by joshhunt** [comment]
all good alexcpsec - I'm doing the raid gear right now.

**Comment by alexcpsec** [comment]
Awesome! Thanks for all your work! :)

**Pull request merged**
