### PR TITLE
Cooperative Emblems and Reorganization

### PR DESCRIPTION
**Pull request by Trekoid**
- Reorganized sections so they are in the same places on base game page and CoO page, i.e. Trials of the Nine is now in Endgame on both pages
- Added missing Dawning Emblem
- Added Cooperative section to Endgame group for gear from stories, strikes, adventures, and public events
- Added Promotional section under Other group for emblems that are obtained from activities outside of playing the game or are promotional in nature, i.e. free with purchase

### CODE REVIEW

**Comment by alexcpsec** [comment]
👍

**Comment by joshhunt** [comment]
👍 this is a bit too much for me to review from Github, so ill check this out sometime this week and see how it goes.

I am kind of wondering though about the right place for all these emblems... I agree more organisation and categorisation for them is needed though.

**Comment by alexcpsec** [comment]
My 2c: organizing the emblems by "giver" like this is what makes the most sense to me.

**Comment by Trekoid** [comment]
I can understand the concerns regarding the organization. The biggest difference is there are a lot of places to get emblems from that do not drop other kinds of loot, so they feel like outliers. Some of this will change, as Bungie has plans for strike and nightfall specific loot, so perhaps in the future these will have more items to group them with.

**Comment by Trekoid** [comment]
Well, it looks like the Loot Cave emblems became ornaments/variants on the new Destination Emblems, which are now all sold by the respective planetary NPC after 10 packages.
I have updated this PR to now:
- Added Destination Emblems to all Planetary Vendors
- Moved all emblems I had in Cooperative section to respective NPC vendors under new subsections titled "Achievement Emblems" since they are unlocked by certain criteria instead of random drops from faction packages.

Strike related emblems to Zavala
screen shot 2018-02-28 at 3 35 55 am

Story related emblems to Ikora
screen shot 2018-02-28 at 3 36 03 am

Public space emblems to Cayde-6, since those are their specialties

- I added all of the new Nightfall specific emblems to the Tactician section under the DLC page
screen shot 2018-02-28 at 3 36 37 am

**Comment by joshhunt** [comment]
Yeah, it's going to be interesting to see how these will show up in the inventory. I can see variations represented as plugs/sockets, but I'm unsure how they'll come through in the Inventory part of the problem. 

Have you got any of the new variations unlocked? Do they automatically show up as obtained on Destiny Sets?

**Comment by Trekoid** [comment]
Using your test page at /newemblems, I have a few of the class specific ones unlocked on the new Crucible emblem. They seem to be registering as obtained, but you have to got set it once for it to register as obtained it looks like.
screen shot 2018-02-28 at 12 48 57 pm

The previews seem to be working as well.
screen shot 2018-02-28 at 12 50 04 pm

**Pull request merged**
