### PR TITLE
More Mercury Emblems

### PR DESCRIPTION
**Pull request by Jakosaur**
Added Fields of Glass & Prophetic Arsenal Emblems

### CODE REVIEW

**Comment by Jakosaur** [comment]
Didn't see the Promotional Emblems on the Base Game page.

**Comment by Jakosaur** [comment]
Updated. Was going to add the new Sonic Simulation emblem to the Promotional Emblems section but doesn't appear to be in the D2 Database yet.

**Comment by Trekoid** [comment]
The hash ID for Sonic Simulation is 1940590825, // Sonic Simulation. It is currently classified, so it won't show up in the DB yet. I opened an issue with the Bungie API directly: https://github.com/Bungie-net/api/issues/429

**Comment by Trekoid** [comment]
You beat me to my missing emblems! As I was playing tonight I noticed I missed replacing "Mercury Treasure Seeker" with "Fields of Glass". Anywhoo, I didn't see this before creating my PR. whoops.

**Pull request closed without merging**
