### PR TITLE
Added known weapons from Gunsmith Arsenal, Warmind

### PR DESCRIPTION
**Pull request by rissajeanne**
Source: https://www.youtube.com/watch?v=X-MjnY4l7Iw

Seems like there should be more in the list, but these are the ones I know about so far.

### CODE REVIEW

**Comment by rissajeanne** [comment]
> I'm curious - based on your other PR, did you actually run this locally to check the changes? If you did, I'm curious to know what that processes was like for you - did you use my instructions, how did you find them, any unexpected slowdowns (apart from the styles variable 🙈)

Yes, I ran it locally using your readme instructions. I found your repo via the Github link on destinysets.com.

I got the dependencies installed with no problem. I'm using node v9.3.0. There's a typo in the readme (line 16); you have `yarn install` where it should say `yarn start`. But no biggie.

Aside from that, the only outstanding issue I'm running into is this error when I connect the local app to my bungie.net account:

screenshot 2018-06-26 15 34 14

If I dismiss the error, I can still run the app just fine, so I haven't bothered to investigate. Any ideas, though?

**Comment by joshhunt** [comment]
Ahhh okay, i know what that one is. Yeah, you can dismiss it and it'll be fine. Thanks for letting me know about that - ill get a fix for it so it doesnt bother you

**Comment by joshhunt** [comment]
in the mean time, putting `REACT_APP_PREVENT_STATS=true` in your .env.local file will prevent that. I'll work to make that the default

**Comment by rissajeanne** [comment]
> in the mean time, putting REACT_APP_PREVENT_STATS=true in your .env.local file will prevent that. I'll work to make that the default

nice, thanks!

**Pull request merged**
