### PR TITLE
Adding missing class items and PS4 exclusive sets

### PR DESCRIPTION
**Pull request by alexcpsec**
Title. Going to look into ghosts and sparrows next.

### CODE REVIEW

**Comment by joshhunt** [comment]
Incredible work, thanks for this (and the others)!

I've only just seen it as I don't get emails for this repo (since fixed), but I'll take a look at this over the coming days. Thanks for the hectic contributions

**Comment by alexcpsec** [comment]
No worries. destinySets has been my main tool in checking my completion rate and I want to make sure it has everything I care about. :)

BTW, I have not really reviewed the code, but do you pull data from the Collection kiosk as well? If so, I'm happy to put together Emblems and Emotes lists for you.

**Comment by joshhunt** [comment]
Yeah, collections are brought in. An emblem and emote list "should just work", but that one actually seems like a good candidate to do automatically, like how the exotic list is done...

**Comment by alexcpsec** [comment]
Hmm, fair. Emotes would be straightforward list from Eververse, but I was thinking of replicating this structure for Emblems: https://www.reddit.com/r/DestinyTheGame/comments/72asib/list_of_emblems_and_where_to_find_them/

I don't think you can collect the ones you DON'T have on either of them.

I'm happy to do the legwork on the item IDs and send them over to you as a PR on the current structure and you can decide what the best strategy is.

**Comment by joshhunt** [comment]
yeah. lets hold off on any other items at the moment. I've added new functionality to literally do what you've mentioned in the sets.js file, but I'm thinking i might want another UI approach to these catch-all 'category' collections (seeing as they're less of a collection and more of a dump of items :)

**Comment by alexcpsec** [comment]
Sure, let me know if there is any other way I can help.

**Pull request merged**
