### PR TITLE
Solstice of Heroes Armour/Ornaments

### PR DESCRIPTION
**Pull request by Jakosaur**

### CODE REVIEW

**Comment by Jakosaur** [comment]
Had to push a fix, it seems the Data Explorer collection mode adds commas at the end of the comment instead of the hash.

**Comment by joshhunt** [comment]
🙈 yeah, I saw that the other day. I'll fix!

I'll check this out properly over the coming days!

**Comment by joshhunt** [comment]
Hmmm... this'll be interesting.  I'm sure you probably saw, but the green / blue gear also exist as ornaments.  

Also maybe you could use `itemGroups` instead to put each class (legendary/blue/purple) on it's own row?

```
name: 'Hunter Armor',
itemGroups: [
    [
        1506728251, // Solstice Mask (Scorched)
        3007586538, // Solstice Grasps (Scorched)
        780038942, // Solstice Vest (Scorched) 
        2046798468, // Solstice Strides (Scorched)
        109666087, // Solstice Cloak (Scorched)
    ],
    [
        2065460339, // Solstice Mask (Rekindled) 
        3853434114, // Solstice Grasps (Rekindled)
        2319743206, // Solstice Vest (Rekindled)
        1644189372, // Solstice Strides (Rekindled)
        2637837647, // Solstice Cloak (Rekindled)
    ], 
    [
        622966241, // Solstice Mask (Resplendent)
        1460885752, // Solstice Grasps (Resplendent)
        222565136, // Solstice Vest (Resplendent)
        3791120690, // Solstice Strides (Resplendent)
        3444687693 // Solstice Cloak (Resplendent)
    ]
]
```

**Comment by Jakosaur** [comment]
Idk whether to keep both the Ornaments and Armour as say someone only gets up to the Rare set, the Uncommon Ornaments would be unlocked but they're still on the Rare Armour. Maybe just tidy them all up into itemGroups for now?

Did they say whether the Solstice of Heroes stuff will be added to the Collections Endpoint before Forsaken? Haven't really been keeping up with the updates haha

**Pull request merged**
