### PR TITLE
Eater of Worlds Emblem & Raid Ghost Merge + Mercury Emblems

### PR DESCRIPTION
**Pull request by Jakosaur**
Added the Eater of Worlds Emblem and merged the Ghost into a 'Extras' section

### CODE REVIEW

**Comment by Trekoid** [comment]
@Jakosaur thanks for this. I was going to tackle emblems on the expansion next, but it seems you've beat me to it.

**Comment by Jakosaur** [comment]
@Trekoid NP, I forgot to add the rest of the Mercury emblems to the gear section. I'll try and do a pull request later or tomorrow

Emblems - Crossroads Emblem, Mercury Treasure Seeker, Prophetic Arsenal, Transit of Mercury

**Comment by Trekoid** [comment]
@Jakosaur I included those in #67

**Comment by Jakosaur** [comment]
@Trekoid Nice, thanks

**Pull request merged**
